### PR TITLE
Unearthed Arcana 2023: Player's Handbook Playtest 7

### PR DESCRIPTION
**Pull request by revilowaldow**
Mostly a placeholder for now

### CODE REVIEW

**Comment by revilowaldow** [comment]
Hey G what's your policy on this stuff? 
image

For *actually* identical stuff:

- Just copy paste and slap the new source on it? 
- add `otherSources` in an earlier prerelease?
- Not add it at all?

**Comment by TheGiddyLimit** [comment]
for the most part it's been option 1: copy-paste, with the odd back-reference if something isn't explicitly reprinted

given that these UAs are now self-contained brew-like docs I'm less worried about minimizing duplicates/etc. That said, I'm less worried _in general_, so if you feel strongly about it one way or the other, then follow ur heart

**Comment by revilowaldow** [comment]
That's everything except the classes, (most)subclasses, their features and optional features. This is probably where I'll leave this for a while now.

**Comment by TheGiddyLimit** [comment]
already a huge help, tyvm!

**Comment by revilowaldow** [comment]
This looks new; I'll just put it in as "other" for now, but it might merit a custom `spellcasting` type prerequisite in future. Could see one being flexible in the format below or could just be a straightforward const true.
```json
"spellcastingClassLevel": {
	"class": [
		"Bard",
		"warlock",
		"etc"
	],
	"level": {
		"min": 1,
		"max": 3,
		"exact": 0
	}
},
```
image

**Comment by TheGiddyLimit** [comment]
my reading of that would be "it doesn't matter how you got this Warlock cantrip" so will go with:
```json
"prerequisite": [
	{
		"spell": [
			{
				"choose": "level=0|class=Warlock",
				"entry": "At Least One Warlock Cantrip"
			}
		]
	}
],
```
for now I reckon. A bit clunky but some shorthand `{"anyWarlockCantrip": true}` or w/e could be made in future as required

**Pull request merged**
