### PR TITLE
feat(UADragonmarks): Add missing UA article

### PR DESCRIPTION
**Pull request by revilowaldow**
Might be nice for Plutonium to support named ability score choices like named additional spell choices:
(see Greater Dragonmark feat)
image
image

### CODE REVIEW

**Comment by revilowaldow** [comment]
Additionally, the abbreviation for this article (`UAD`) conflicts with the abbreviation for both UA: Downtime and UA: Druid, which already conflict with each other.

**Comment by revilowaldow** [comment]
I've further added the missing UA Magic Items of Eberron
Note that this is blocked behind schema permission for `"reqAttune` and `reqAttuneTags` for `baseitem`s
This feels odd but it's due to Armblades in the UA being `baseitem`s rather than a `magicvariant` as per the final version
image

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
> named ability score choices

not a piece of UI I feel like overhauling at this exact moment, but will put in a feature request

> Could move to `UADra`, `UADow`, `UADru` but that looks untidy...

seems tidy enough to me; `UAD` is pretty meaningless

maybe `UADrgM`, `UADown`, `UADrui`, or something along those "give it a bit of a hint" lines

> Armblades

not a fan of the `baseitem` hack tbh; as I see it

pros:

- can get specific variants

cons:

- can't get armblades of homebrew items
- can't get armblades of '24 items
- the `{@i any one-handed melee weapon}` line is nasty
- requires a cross-product explosion of `reqAttuneTags` when making specific variants
- is hacky

I'm not convinced that pro is big enough to justify all the jank. As a Warforged enjoyer I'd rather have the full range of weapons on the table, and manually tack magic version stuff onto my sheet if I really need it later

maybe an `Armblade` `magicvariant`, plus `Armblade (Vorpal)` and `Armblade (Vicious)` `magicvariant`s as a sampler, instead?

**Comment by revilowaldow** [comment]
Cheers for feedback, will make changes tomorrow, or potentially later in the week.

Happy to make all the changes suggested and go with the magic variant style instead.

**Comment by revilowaldow** [comment]
Needs schema bumping to accommodate new `itemsHidden` boolean

**Comment by revilowaldow** [comment]
Should be good to go :)

**Review by TheGiddyLimit — APPROVED** [review]
lovely stuff

**Pull request merged**
